apiVersion: v2
name: sda-svc
version: 0.1
description: Components for Sensitive Data Archive (SDA) installation
home: http://localega.readthedocs.io
icon: https://neic.no/assets/images/logo.png
sources:
- https://github.com/neicnordic/sda-helm
