{{- if .Values.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-ingress-other-namespaces
  namespace: {{ .Release.Namespace }}
  spec:
    ingress:
    - from:
      - podSelector: {}
    podSelector: {}
    policyTypes:
    - Ingress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: broker-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      role: broker
  policyTypes:
  - Ingress
  ingress:
  - from:
  {{- if .Values.networkPolicy.twoClusterSetup }}
    - ipBlock:
        cidr: {{ .Values.networkPolicy.externalClusterIp }}
  {{- else }}
    - podSelector:
        matchLabels:
          {{ .Values.networkPolicy.nsprefix }}mq: allowtraffic
      namespaceSelector:
        matchLabels:
          networkpolicy: {{ .Values.networkPolicy.nsprefix }}sda-internal
  {{- end }}
    - podSelector:
        matchLabels:
          {{ .Values.networkPolicy.nsprefix }}mq: allowtraffic
      namespaceSelector:
        matchLabels:
          networkpolicy: {{ .Values.networkPolicy.nsprefix }}sda-external
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
---
{{- end }}
