{{- define "mqfullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

---
apiVersion: v1
kind: Secret
metadata:
  name: sda-mq-test-certs
type: Opaque
data:
  {{- (.Files.Glob "files/{tester,CA,ca}*").AsSecrets | nindent 2 }}

  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sda-mq-test-app
data:
  {{- (.Files.Glob "files/test.py").AsConfig | nindent 2 }}

---

apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-test"
  resourceVersion: {{ template "mqfullname" . }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  containers:
    - name: {{ .Release.Name }}-test
      image: alpine:latest
      imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
      volumeMounts:
      {{- if not .Values.externalPkiService.tlsPath }}
        - name: certs
          mountPath: /certs
      {{- end }}
      env:
        {{- if .Values.externalPkiService.tlsPath }}
        - name: PKI_VOLUME_PATH
          value: {{.Values.externalPkiService.tlsPath }}
        {{- end }}
        - name: MQ_HOST
          value: {{ template "mqfullname" . }}
      command: [ "/bin/sh" ]
      args:
        - "-x"
        - "-c"
        - 'P=${PKI_VOLUME_PATH:-/certs}; 
           apk add openssl;
           count=1;
           until openssl s_client -connect "${MQ_HOST}:5671" -verify 50 -key "$P/tester.ca.key" -cert "$P/tester.ca.crt" -verify_return_error -verifyCAfile "$P/ca.crt" </dev/null; do
             sleep 5;
             count=$((count+1));
             if [ "$count" -gt 10 ]; then
               exit 1;
             fi;
           done;
           exit 0'
  volumes:
    {{- if not .Values.externalPkiService.tlsPath }}
      - name: certs
        projected:
          sources:
          - secret:
              name: sda-mq-test-certs
              items:
              - key: tester.ca.key
                path: tester.ca.key
              - key: tester.ca.crt
                path: tester.ca.crt
              - key: ca.crt
                path: ca.crt
    {{- end }}
  restartPolicy: Never

