{{ if .Values.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-access
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          networkpolicy: kube-system
    ports:
    - protocol: UDP
      port: 53
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: db-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{ .Values.networkPolicy.databaseNamespace }}: allowtraffic
  policyTypes:
  - Egress
  egress:
  - to:
  {{- if .Values.db.external }}
    - ipBlock:
        cidr: {{ .Values.db.ip }}/32
  {{- else }}
    - podSelector:
        matchLabels:
          role: database
    {{- if .Values.networkPolicy.databaseNamespace }}
      namespaceSelector:
        matchLabels:
          networkpolicy: {{ .Values.networkPolicy.databaseNamespace }}
    {{- end }}
  {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.db.port }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: broker-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      {{ .Values.networkPolicy.brokerNamespace }}: allowtraffic
  policyTypes:
  - Egress
  egress:
  - to:
  {{- if .Values.broker.external }}
    - ipBlock:
        cidr: {{ .Values.broker.ip }}/32
  {{- else }}
    - podSelector:
        matchLabels:
          role: broker
    {{- if .Values.networkPolicy.brokerNamespace }}
      namespaceSelector:
        matchLabels:
          networkpolicy: {{ .Values.networkPolicy.brokerNamespace }}
    {{- end }}
  {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.broker.port }}
---
{{- end }}