{{- if .Values.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-access
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          name: kube-system
    ports:
    - protocol: UDP
      port: 53
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: sda-orch
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ template "sda.fullname" . }}
  policyTypes:
  - Egress
  egress:
  - to:
    {{- if .Values.networkPolicy.brokerNamespace }}
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.brokerNamespace }}
    {{- end }}
    - podSelector:
        matchLabels:
          role: database
  {{- end }}
    ports:
    - protocol: TCP
      port: 5432
    {{- if .Values.networkPolicy.databaseNamespace }}
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.databaseNamespace }}
    {{- end }}
    - podSelector:
        matchLabels:
          role: broker
  {{- end }}
    ports:
    - protocol: TCP
      port: 5672
{{- if .Values.global.inbox.ingressips }}
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: inbox-ingress-policy
  namespace: {{ .Release.Namespace }}
spec:
    matchLabels:
      role: inbox
  policyTypes:
  - Ingress
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.global.inbox.ingressips }}
{{- end }}
---
{{- end }}
