{{- if not .Values.secretsService }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-orchestrate
type: Opaque
data:
  dbinUser: {{ include "dbInUser" . | b64enc }}
  dbinPass: {{ include "dbInPass" . | b64enc }}
  dbOutUser: {{ include "dbOutUser" . | b64enc }}
  dbOutPass: {{ include "dbOutPass" . | b64enc }}
  mqPassword: {{ include "mqPass" . | b64enc }}
{{- end }}
{{- if not .Values.pkiService }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-orchestrate-certs
data:
{{ ( .Files.Glob "files/root.ca.crt" ).AsSecrets | trim | indent 2 }}
{{ ( .Files.Glob "files/cert.ca.crt" ).AsSecrets | trim | indent 2 }}
{{ ( .Files.Glob "files/cert.ca.key" ).AsSecrets | trim | indent 2 }}
{{- end }}