{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not  .Values.global.deploymentType) }}
{{- if eq "S3Storage" .Values.global.inbox.storageType }}
{{- $jwtKey := .Files.Glob (printf "files/%s" .Values.global.auth.jwtKey) }}
{{- if or $jwtKey (not .Values.global.confFile) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-auth
type: Opaque
data:
{{- if $jwtKey }}
{{ ( $jwtKey ).AsSecrets | indent 2 }}
{{- end }}
{{- if not .Values.global.confFile }}
  elixirID: {{ .Values.global.auth.elixirID | quote | trimall "\"" | b64enc }}
  elixirSecret: {{ .Values.global.auth.elixirSecret | quote | trimall "\"" | b64enc }}
  cegaID: {{ .Values.global.cega.user | quote | trimall "\"" | b64enc }}
  cegaSecret: {{ .Values.global.cega.password | quote | trimall "\"" | b64enc }}
{{- end }}
{{- end }}
{{- if and .Values.global.auth.useTLS (not .Values.global.pkiService) }}
---
{{- $auth := .Files.Glob "files/auth*" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sda.fullname" . }}-auth-certs
data:
{{ ( .Files.Glob "files/ca.crt" ).AsSecrets | trim | indent 2 }}
{{ ( $auth ).AsSecrets | indent 2 }}
{{- end }}
{{- end }}
{{- end }}
