{{- if or (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
{{- if eq "s3" .Values.global.inbox.storageType }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sda.fullname" . }}-auth
  labels:
    role: auth
    app: {{ template "sda.fullname" . }}-auth
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.auth.name }}"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.auth.replicaCount }}
  revisionHistoryLimit: {{ default "3" .Values.global.revisionHistory }}
  selector:
    matchLabels:
      app: {{ template "sda.fullname" . }}-auth
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sda.fullname" . }}-auth
        role: auth
        release: {{ .Release.Name }}
      annotations:
        {{- if not .Values.global.confFile }}
        checksum/secret: {{ include (print $.Template.BasePath "/auth-secrets.yaml") . | sha256sum }}
        {{- end }}
{{- if .Values.global.podAnnotations }}
{{- toYaml .Values.global.podAnnotations | nindent 8 -}}
{{- end }}
{{- if .Values.auth.annotations }}
{{- toYaml .Values.auth.annotations | nindent 8 -}}
{{- end }}
    spec:
    {{- if .Values.global.rbacEnabled}}
      serviceAccountName: {{ .Release.Name }}
    {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: auth
        image: "{{ .Values.auth.repository }}:{{ .Values.auth.imageTag }}"
        imagePullPolicy: {{ .Values.auth.imagePullPolicy | quote }}
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: LOG_LEVEL
          value: {{ upper .Values.global.log }}
      {{- if not .Values.global.confFile }}
        - name: ELIXIR_ID
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-auth
              key: elixirID
        - name: ELIXIR_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-auth
              key: elixirSecret
        - name: CEGA_ID
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-auth
              key: cegaID
        - name: CEGA_SECRET
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-auth
              key: cegaSecret
      {{- else }}
        - name: CONF_FILE_PATH
          value: {{ include "confFile" . }}
      {{- end }}
        - name: ELIXIR_REDIRECT_URI
          value: "https://{{ .Values.global.ingress.hostName.auth }}/elixir/login"
        - name: ELIXIR_AUTH_URL
          value: "{{ .Values.global.elixir.oidcdHost }}/oidc/authorize"
        - name: ELIXIR_TOKEN_URL
          value: "{{ .Values.global.elixir.oidcdHost }}/oidc/token"
        - name: ELIXIR_CERTS_URL
          value: "{{ .Values.global.elixir.oidcdHost }}/oidc/jwk"
        - name: ELIXIR_USERINFO_URL
          value: "{{ .Values.global.elixir.oidcdHost }}/oidc/userinfo"
        - name: ELIXIR_ISSUER_URL
          value: "{{ .Values.global.elixir.oidcdHost }}/oidc"
        - name: ELIXIR_REVOCATION_URL
          value: "{{ .Values.global.elixir.oidcdHost }}/oidc/revoke"
        - name: ELIXIR_SCOPE
          value: "openid ga4gh_passport_v1"
        - name: CEGA_AUTH_URL
          value: {{ printf "%s%s" (.Values.global.cega.host) "/lega/v1/legas/users/" | quote }}
        - name: JWT_PRIVATE_KEY
          value: "{{ template "secretsPath" . }}/{{ .Values.global.auth.jwtKey }}"
        - name: JWT_SIGNATURE_ALG
          value: {{ .Values.global.auth.jwtAlg | quote }}
        - name: BIND_ADDRESS
          value: "0.0.0.0"
        - name: PORT
          value: {{ ternary 8080 8443 ( empty .Values.global.auth.useTLS ) | quote }}
        - name: SERVER_NAME
          value: {{ .Values.global.ingress.hostName.auth | quote }}
        - name: URL_SCHEME
          value: {{ ternary "http" "https" ( empty .Values.global.auth.useTLS ) | quote }}
        - name: SECRET_KEY
          value: {{ randAlphaNum 12 | quote }}
        - name: ENABLE_TLS
          value: {{ toString .Values.global.auth.useTLS | camelcase | quote }}
        {{- if .Values.global.auth.useTLS }}
        - name: CERT_FILE
          value: "{{ template "tlsPath" . }}/auth.crt"
        - name: KEY_FILE
          value: "{{ template "tlsPath" . }}/auth.key"
        {{- if .Values.global.auth.cacert }}
        - name: CA_CERTS
          value: "{{ template "tlsPath" . }}/ca.crt"
        {{- end }}
        {{- end }}
        ports:
        - name: auth
          containerPort: {{ ternary 8080 8443 ( empty .Values.global.auth.useTLS ) }}
          protocol: TCP
        livenessProbe:
          httpGet:
            port: auth
            path: /
            scheme: {{ ternary "HTTP" "HTTPS" ( empty .Values.global.auth.useTLS ) }}
            httpHeaders:
            - name: Host
              value: {{ .Values.global.ingress.hostName.auth }}
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            port: auth
            path: /
            scheme: {{ ternary "HTTP" "HTTPS" ( empty .Values.global.auth.useTLS ) }}
            httpHeaders:
            - name: Host
              value: {{ .Values.global.ingress.hostName.auth }}
          periodSeconds: 5
        resources:
{{ toYaml .Values.s3Inbox.resources | trim | indent 10 }}
        volumeMounts:
      {{- if not .Values.global.pkiService }}
        - name: tls
          mountPath: {{ include "tlsPath" . }}
      {{- end }}
      {{- if and .Values.global.auth.jwtkey .Values.global.jwtPath }}
        - name: jwt
          mountPath: {{ include "jwtPath" . }}
      {{- end }}
      volumes:
      {{- if and .Values.global.auth.jwtKey .Values.global.jwtPath }}
        - name: jwt
          projected:
            defaultMode: 0440
            sources:
            - secret:
                name: {{ template "sda.fullname" . }}-auth
                items:
                  - key: {{ .Values.global.auth.jwtKey }}
                    path: {{ .Values.global.auth.jwtKey }}
      {{- end }}
      {{- if not .Values.global.pkiService }}
        - name: tls
          secret:
            defaultMode: 0440
            secretName: {{ template "sda.fullname" . }}-auth-certs
      {{- end }}
{{- end }}
{{- end }}
