{{ if .Values.global.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-ingress-other-namespaces
  namespace: {{ .Release.Namespace }}
spec:
    ingress:
    - from:
      - podSelector: {}
    podSelector: {}
    policyTypes:
    - Ingress
---
{{- if  or  (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: doa
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      role: doa
  ingress:
  - from:
    - ipBlock:
        cidr: {{ .Values.global.doa.ingressips }}
    ports:
    - protocol: TCP
      port: {{ .Values.global.doa.servicePort }}
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.global.doa.egressips }}
    ports:
    - protocol: TCP
      port: {{ .Values.global.doa.egressPort }}
---
{{- end }}
{{- if  or  (or (eq "all" .Values.global.deploymentType) (eq "external" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: inbox
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      role: inbox
  ingress:
  - from:
    - ipBlock:
        cidr: {{ .Values.global.inbox.ingressips }}
    ports:
    - protocol: TCP
      port: {{ .Values.global.inbox.servicePort }}
  egress:
  - to:
    - ipBlock:
        cidr: {{ .Values.global.inbox.egressips }}
    ports:
    - protocol: TCP
      port: {{ .Values.global.inbox.egressPort }}
{{- end }}
{{- end }}
