{{- if  or  (or (eq "all" .Values.global.deploymentType) (eq "internal" .Values.global.deploymentType) ) (not .Values.global.deploymentType) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "sda.fullname" . }}-verify
  labels:
    role: verify
    app: {{ template "sda.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: {{ .Release.Name }}-verify
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  revisionHistoryLimit: {{ default "3" .Values.global.revisionHistory }}
  selector:
    matchLabels:
      app: {{ template "sda.name" . }}-verify
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "sda.name" . }}-verify
        role: verify
        release: {{ .Release.Name }}
      annotations:
        {{- if not .Values.global.confFile }}
        checksum/secret: {{ include (print $.Template.BasePath "/shared-secrets.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/verify-secrets.yaml") . | sha256sum }}
        {{- end }}
{{- if .Values.global.podAnnotations }}
{{- toYaml .Values.global.podAnnotations | nindent 8 -}}
{{- end }}
{{- if .Values.verify.annotations }}
{{- toYaml .Values.verify.annotations | nindent 8 -}}
{{- end }}
    spec:
    {{- if .Values.global.rbacEnabled}}
      serviceAccountName: {{ .Release.Name }}
    {{- end }}
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
    {{- if .Values.global.pkiPermissions }}
      initContainers:
      - name: tls-init
        image: busybox
        command: ["/bin/sh", "-c"]
        args: ["/bin/cp /tls-certs/* /tls/ && chown 1000:1000 /tls/* && chmod 0600 /tls/*"]
        securityContext:
          allowPrivilegeEscalation: false
        volumeMounts:
        - name: tls-certs
          mountPath: /tls-certs
        - name: tls
          mountPath: /tls
    {{- end }}
      containers:
      - name: verify
        image: "{{ .Values.verify.repository }}:{{ .Values.verify.imageTag }}"
        imagePullPolicy: {{ .Values.verify.imagePullPolicy | quote }}
        command: ["ega-verify"]
        args: ["--log", {{ .Values.global.log | quote }} {{- if .Values.global.confFile -}} , "--conf", "{{ template "confFile" . }}" {{- end -}}]
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: ARCHIVE_STORAGE_DRIVER
        {{- if eq "FileStorage" .Values.global.archive.storageType }}
          value: "FileStorage"
        - name: ARCHIVE_LOCATION
          value: "{{ .Values.global.archive.volumePath }}/%s"
        {{ else }}
          value: S3Storage
        - name: ARCHIVE_S3_URL
          value: {{ required "S3 archive URL missing" .Values.global.archive.s3Url }}
        - name: ARCHIVE_S3_BUCKET
          value: {{ required "S3 archive bucket missing" .Values.global.archive.s3Bucket }}
        - name: ARCHIVE_S3_REGION
          value: {{ default "us-east-1" .Values.global.archive.s3Region }}
        - name: ARCHIVE_S3_CHUNK_SIZE
          value: {{  .Values.global.archive.s3ChunkSize | mul 1048576 | quote }}
        {{- end }}
        - name: BROKER_CACERTFILE
          value:  "{{ template "tlsPath" . }}/ca.crt"
        - name: BROKER_CERTFILE
          value:  "{{ template "tlsPath" . }}/verify.crt"
        - name: BROKER_KEYFILE
          value:  "{{ template "tlsPath" . }}/verify.key"
        - name: BROKER_VERIFY_HOSTNAME
          value: "false"
        - name: BROKER_VERIFY_PEER
          value: {{ .Values.global.broker.verifyPeer | quote }}
        {{- if not .Values.global.confFile }}
        - name: C4GH_FILE_FILEPATH
          value: "{{ template "c4ghPath" . }}/{{ .Values.global.c4gh.file }}"
        - name: C4GH_FILE_PASSPHRASE
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-c4gh
              key: passphrase
        - name: BROKER_CONNECTION
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-verify
              key: mqConnection
        - name: DB_CONNECTION
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-verify
              key: dbConnection
        {{- if eq "S3Storage" .Values.global.archive.storageType }}
        - name: ARCHIVE_S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-s3archive-keys
              key: s3ArchiveAccessKey
        - name: ARCHIVE_S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: {{ template "sda.fullname" . }}-s3archive-keys
              key: s3ArchiveSecretKey
        {{- end }}
        {{- end }}
        resources:
{{ toYaml .Values.verify.resources | trim | indent 10 }}
        volumeMounts:
        {{- if (.Values.global.log | lower) eq "debug" }}
        - name: tmp
          mountPath: /tmp
        {{- end }}
        {{- if not .Values.global.confFile }}
        - name: c4gh
          mountPath: {{ template "c4ghPath" . }}
        {{- end }}
        {{- if not .Values.global.pkiService }}
        - name: tls
          mountPath: {{ template "tlsPath" . }}
        {{- end }}
        {{- if eq "FileStorage" .Values.global.archive.storageType }}
        - name: archive
          mountPath: {{ .Values.global.archive.volumePath | quote }}
        {{- end }}
      volumes:
    {{- if (.Values.global.log | lower) eq "debug" }}
        - name: tmp
          emptyDir:
            medium: Memory
    {{- end }}
    {{- if not .Values.global.pkiService }}
        - name: {{ ternary "tls" "tls-certs" (empty .Values.global.pkiPermissions) }}
          secret:
            defaultMode: 0440
            secretName: {{ template "sda.fullname" . }}-verify-certs
      {{- if .Values.global.pkiPermissions }}
        - name: tls
          emptyDir:
            medium: Memory
            sizeLimit: 10Mi
      {{- end }}
    {{- end }}
      {{- if not .Values.global.confFile }}
        - name: c4gh
          secret:
            defaultMode: 0440
            secretName: {{ template "sda.fullname" . }}-c4gh
            items:
            - key: {{ .Values.global.c4gh.file }}
              path: {{ .Values.global.c4gh.file }}
      {{- end }}
      {{- if eq "FileStorage" .Values.global.archive.storageType }}
        - name: archive
        {{- if .Values.global.archive.existingClaim }}
          persistentVolumeClaim:
            claimName: {{ .Values.global.archive.existingClaim }}
        {{- else }}
          nfs:
            server: {{ required "An archive NFS server is required" .Values.global.archive.nfsServer | quote }}
            path: {{ if .Values.global.archive.nfsPath }}{{ .Values.global.archive.nfsPath | quote }}{{ else }}{{ "/" }}{{ end }}
        {{- end }}
      {{- end }}
      restartPolicy: Always
{{- end }}
