{{- if .Values.networkPolicy.create }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-all
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-dns-access
  namespace: {{ .Release.Namespace }}
spec:
  podSelector: {}
  policyTypes:
  - Egress
  egress:
  - to:
    - namespaceSelector:
        matchLabels:
          kube-system: networkpolicy
    ports:
    - protocol: UDP
      port: 53
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: db-policy
  namespace: {{ .Release.Namespace }}
spec:
  podSelector:
    matchLabels:
      role: database
  policyTypes:
  - Ingress
  ingress:
  - from:
  {{- if .Values.networkPolicy.twoClusterSetup }}
    - ipBlock:
        cidr: {{ .Values.networkPolicy.externalClusterIp }}
  {{- else }}
    - podSelector:
        matchLabels:
          {{ .Values.networkPolicy.nsprefix }}db: allowtraffic
      namespaceSelector:
        matchLabels:
          networkpolicy: {{ .Values.networkPolicy.nsprefix }}sda-internal
    - podSelector:
        matchLabels:
          {{ .Values.networkPolicy.nsprefix }}db: allowtraffic
      namespaceSelector:
        matchLabels:
          networkpolicy: {{ .Values.networkPolicy.nsprefix }}sda-orch
  {{- end }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
---
{{- end }}
