{{- define "dbfullname" -}}
{{- if .Values.fullnameOverride -}}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- $name := default .Chart.Name .Values.nameOverride -}}
{{- if contains $name .Release.Name -}}
{{- .Release.Name | trunc 63 | trimSuffix "-" -}}
{{- else -}}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" -}}
{{- end -}}
{{- end -}}
{{- end -}}

apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-test"
  resourceVersion: {{ template "dbfullname" . }}
  annotations:
    "helm.sh/hook": test
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  securityContext:
    runAsUser: 70
    fsGroup: 70
  containers:
    - name: {{ .Release.Name }}-test
      image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
      imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
      volumeMounts:
      {{- if not .Values.externalPkiService.tlsPath }}
        - name: tls-certs
          mountPath: {{ .Values.persistence.mountPath }}/tls
      {{- end }}
      env:
        - name: DB_HOST
          value: "{{ template "dbfullname" . }}"
        - name: PGSSL
          value: /var/lib/postgresql/.postgresql/
        - name: PGSSLMODE
          value: verify-full
        - name: PGPASSWORD
          valueFrom:
              secretKeyRef:
                name: {{ template "dbfullname" . }}
                key: pgInPasswd             
      command: [ "/bin/bash" ]
      args:
        - "-c"
        - 'cd $HOME;
           mkdir -p $PGSSL;
           cp tls/pg.key $PGSSL/postgresql.key;
           cp tls/pg.crt $PGSSL/postgresql.crt;
           cp tls/CA.crt $PGSSL/root.crt;
           chmod -R og-rw $PGSSL;
           count=1;
           until (psql -h ${DB_HOST} -U lega_in lega -c "select * from local_ega.dbschema_version" || [ "$count" -ge 10 ]); do 
             sleep 10;
             count=$((count+1));
           done |
           grep -F "Created with version"'
  volumes:
    {{- if not .Values.externalPkiService.tlsPath }}
      - name: tls-certs
        projected:
          defaultMode: 0440
          sources:
          - secret:
              name: {{ template "dbfullname" . }}
              items:
              {{- if .Values.global.verifyPeer }}
              - key: CA.crt
                path: CA.crt
              {{- end }}
              - key: pg.crt
                path: pg.crt
              - key: pg.key
                path: pg.key
    {{- end }}
  restartPolicy: Never

