
image:
  repository: neicnordic/sda-orch
  tag: latest
  pullPolicy: Always
logLevel: "info"

## RevisionHistory
##  If defined, set the revisionHistoryLimit of the deployment, defaults to 3
##  RevisionHistoryLimit is number of old ReplicaSets to retain to allow rollback.
  # revisionHistory: 3

# Annotations applied to pods of all services.
# This should be a multi-line string mapping directly to the a map of
# the annotations to apply to the service pods
podAnnotations: {}

# If an external PKI infrastructure is used set this to true
pkiService: false
# if permissions needs to be set on the injected certificates set this to true
pkiPermissions: true

# Assume RBAC is enabled in the cluster
rbacEnabled: true

podSecurityPolicy:
  create: true

# utilize network isolation
# Make sure you’ve configured a network provider with network policy support.
# There are a number of network providers that support NetworkPolicy, including:
# Calico, Cilium, Kube-router, Romana and Weave Net
networkPolicy:
  create: false
  brokerNamespace: ""

tlsPath: "/tls/certs"

## RevisionHistory
##  If defined, set the revisionHistoryLimit of the deployment, defaults to 3
##  RevisionHistoryLimit is number of old ReplicaSets to retain to allow rollback.
  # revisionHistory: 3

# If an external secrets management service is used set this to true
secretsService: false

# env file for use with secretsservice
envFile: "env"

# used by both Message Broker and Database
sslmode:
  ssl: true
  verifyPeer: true

broker:
  exchange: ""
  host: ""
  password: ""
  port: 5671
  username: ""
  vhost: "/"
  queue:
    inbox: "inbox"
    completed: "completed"
    verify: "verified"
    accessionids: "accessionIDs"
    ingest: "ingest"
    mappings: "mappings"


resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "250m"
